name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        deno-version: [2.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install Node.js dependencies
        run: npm install --no-package-lock

      - name: Run build script
        run: npm run build --if-present

      - name: Ensure repository is clean
        run: |
          git diff --exit-code
          git diff --cached --exit-code

      - name: Report results
        run: npm run test --if-present
